### ISSUE TITLE
DDPG is not training

### ISSUE THREAD

**Issue by bardas** [madras-simulator/MADRaS#18]
I have run about 1000 episodes and the car does not learn to drive. I am running the algorithm with the default params. Also, I have turned the train indicator to 1. Do I have to change something else? Do I miss something?

**Comment by rudrasohan** [comment]
Hi @bardas , can you specify branch you are using and also which ddpg you are using, pid or behavior_reflex.

**Comment by bardas** [comment]
@rudrasohan I am using behavior_reflex

**Comment by rudrasohan** [comment]
And what is the branch that you are using `master` or `Version 1`?

**Comment by bardas** [comment]
@rudrasohan  Version 1

**Comment by mateuszkupper** [comment]
Hi, it's actually not working for me either. The agent does not learn anything and weirdly the first episode is usually the best one. I have also not changed anything in the code. I am using the Version 1 branch.

Thanks

**Comment by buridiaditya** [comment]
You could use master which works with openai baselines. It trains well for me. Ran DDPG for 1e7 time steps. Use the reward function as just this `sp * np.cos(obs['angle'])` at the mentioned location.
https://github.com/madras-simulator/MADRaS/blob/25571bc072b070b9bf41b37d7bdaf54fb6e6f6ac/MADRaS/utils/gym_torcs.py#L141

**Comment by bardas** [comment]
You mean just doing this
progress = sp * np.cos(obs['angle'])  instead of 
progress = sp * np.cos(obs['angle']) - np.abs(sp * np.sin(obs['angle'])) - sp * np.abs(obs['trackPos'])?

**Comment by buridiaditya** [comment]
Yes

**Comment by bardas** [comment]
after how many episodes did it converge? Also, you are running it without changing the parameters you are providing in your code?

**Comment by bardas** [comment]
after how many episodes does it converge? Did you run it with the parameters you are providing in your code or you change them?

**Comment by buridiaditya** [comment]
Don't remember the no of episodes for convergence. Exact same parameters mentioned in code.
