### ISSUE TITLE
How to run baselines experiments?

### ISSUE THREAD

**Issue by Vaselinus** [madras-simulator/MADRaS#20]
When I start any experiment with baselines, the agent waiting for the random port server:
**Waiting for server on 38992............**
I used:
**python -m baselines.run --alg=ddpg --env='Madras-v0'**
With multiple agents it requests different random ports.
TORCS doesn't starts automatically with baselines.

How can I specify agent's port when I am using baselines?

**Comment by buridiaditya** [comment]
TORCS automatically starts from MadrasEnv. If you have set `visualise=True` then you will need `VirtualGL` installed in your system. You could try setting `visualise=False` just for sanity check and run it.

**Comment by Vaselinus** [comment]
Thank you! Now it works.
