### ISSUE TITLE
Hello,I have a question!

### ISSUE THREAD

**Issue by BCWang93** [madras-simulator/MADRaS#22]
Hi,I am very insterested in this project!I want to know,do you have the multi-agent algorithm 'COMA' in this project?Because I need some help about this algorithm.Thank you very much!

**Comment by buridiaditya** [comment]
Hi @BCWang93. There is no multiagent algorithm implemented as of now. But the Madras Env will support multiagent training with your own multiagent algorithm after the merging of this #19 .
