### ISSUE TITLE
Multi Agent Latency Issue

### ISSUE THREAD

**Issue by rudrasohan** [madras-simulator/MADRaS#33]
The Multi-Agent part is showing some latency when the other agents are trying to connect to the simulator.

**Comment by rudrasohan** [comment]
- [Replace with an OrderdDict here](https://github.com/Santara/MADRaS/blob/e26307efb621be8012dd321f15fa187aa12523d9/MADRaS/envs/gym_madras_v2.py#L250) as the order of connection matters.

- [Remove this part](https://github.com/Santara/MADRaS/blob/e26307efb621be8012dd321f15fa187aa12523d9/MADRaS/utils/snakeoil3_gym_v2.py#L283-L286) from the snakeoil_v2.

**Comment by Santara** [comment]
@rudrasohan Could you please implement the two changes in your comment above through a PR? The latency issue was solved by @manish-pra in https://github.com/Santara/MADRaS/pull/6. Although the above were not the reasons for the latency issue, they are important limitations that need to be addressed.

**Comment by manish-pra** [comment]
This also related to the error during shutdown. [here](https://github.com/Santara/MADRaS/blob/e26307efb621be8012dd321f15fa187aa12523d9/MADRaS/utils/gym_torcs_v2.py#L124), I would say pass `obs_pre` through self.make_observation(obs_pre)

**Comment by rudrasohan** [comment]
On it

**Comment by rudrasohan** [comment]
Closing this
